# 1.Gerekli kütüphanelerin eklenmesi

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 2.Veri setinin pandas'a yüklenmesi

In [5]:
#dataset=pd.read_csv("Data.csv") 
#normalde veri seti böyle yükleniyor ama hoca link atmadığı için dataseti elle giricem
dataset={
    "Country":["France","Spain","Germany","Spain","Germany","France","Spain","France","Germany","France"],
    "Age":[44,27,30,38,40,35,np.nan,48,50,37],
    "Salary":[72000,48000,54000,61000,np.nan,58000,52000,79000,83000,67000],
    "Purchased":["No","Yes","No","No","Yes","Yes","No","Yes","No","Yes"]
    }
df=pd.DataFrame(dataset)
print(df)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


# 3. Python ':' Operatorü ve Fonksiyonlar

In [16]:
print(df.values) #veri setini array olarak döndürür
print(type(df.values))
#indexlere ulaşabiliriz mesela ilk satıra ulaşmak için;
print(df.values[0])
#direkt değere de ulaşabiliriz mesela ilk satıdaki fransaya ulaşmak için
print(df.values[0,0])

[['France' 44.0 72000.0 'No']
 ['Spain' 27.0 48000.0 'Yes']
 ['Germany' 30.0 54000.0 'No']
 ['Spain' 38.0 61000.0 'No']
 ['Germany' 40.0 nan 'Yes']
 ['France' 35.0 58000.0 'Yes']
 ['Spain' nan 52000.0 'No']
 ['France' 48.0 79000.0 'Yes']
 ['Germany' 50.0 83000.0 'No']
 ['France' 37.0 67000.0 'Yes']]
<class 'numpy.ndarray'>
['France' 44.0 72000.0 'No']
France


In [19]:
# : -> range operatörüdür
print(df.values[0:2]) # ilk 2 satırı yazdırır

[['France' 44.0 72000.0 'No']
 ['Spain' 27.0 48000.0 'Yes']]


In [24]:
print(df.values[0::2]) #0 dan tüm veriler bitene kadar 2şer atlayarak yazdırır

[['France' 44.0 72000.0 'No']
 ['Germany' 30.0 54000.0 'No']
 ['Germany' 40.0 nan 'Yes']
 ['Spain' nan 52000.0 'No']
 ['Germany' 50.0 83000.0 'No']]


In [21]:
print(df.values[:,2]) #bu işlem ile bütün satırlardaki 2indexe gelen sütunu yazdırır

[72000.0 48000.0 54000.0 61000.0 nan 58000.0 52000.0 79000.0 83000.0
 67000.0]


In [22]:
print(df.values[:,2:]) #2. indexteki ve sonrasında gelen sütunları yazdırır

[[72000.0 'No']
 [48000.0 'Yes']
 [54000.0 'No']
 [61000.0 'No']
 [nan 'Yes']
 [58000.0 'Yes']
 [52000.0 'No']
 [79000.0 'Yes']
 [83000.0 'No']
 [67000.0 'Yes']]


In [12]:
print(df.ndim) #verisetinde kaç boyut olduğunu döndürür

2


In [13]:
print(df.size) # verisetindeki eleman sayısını döndürür

40


In [14]:
print(df.shape) #veri setinin boyutlarını döndürür (satır,sütun)

(10, 4)


In [15]:
print(df.dtypes) #elemanların tipini döndürür

Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object


# 4. Veriyi X ve Y olarak bölme

In [33]:
df.iloc[0] #iloc ilk olarak dataframe olarak çeker 

Country       France
Age             44.0
Salary       72000.0
Purchased         No
Name: 0, dtype: object

In [35]:
df.iloc[0].values # bu şekilde dizi haline getirilir

array(['France', 44.0, 72000.0, 'No'], dtype=object)

In [36]:
x=df.iloc[:,:3].values #ilk 3veriyi aldık (%75e %25 bölmek için)
y=df.iloc[:,3].values # sadece son sütunu aldık 
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# 5.Kayıp değerleri doldurma

In [39]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean') #nan değerleri ortalamaya göre doldurduk
#veriyi tanımlayalım;
imputer.fit(x[:,1:]) #sadece age ve salary değerlerini aldık çünkü ortalama(mean) sadece sayısal değerleri baz alır
x[:,1:]=imputer.transform(x[:,1:])
print(x) 
#nan değerleri mutlaka doldurulmalı yoksa modeli seçemeyiz

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# 6. Etiket olan değerleri numaralandırma

### 6.1 Bağımsız değişkeni numaralandırma

#### OneHotEncoder
* 2'den daha fazla sınıf sayılarında kullanılır
* Etiketleri ünik olarak ikili sayı sisteminde numaralandırılır

* Ülke etiketimiz;
    * Fransa:001
    * İspanya:010
    * Almanya:100

* ( Çok kullanılan işlem değildir)

In [41]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [43]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [44]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


## 6.2 Bağımlı değişkeni numaralandırma

#### LabelEncoder 
* 2 veya daha az sınıf sayılarında kullanılır
* Etiketleri 0 ile sınıf_sayisi-1 aralığında numaralandırılır
* sonuç etiketimiz;
   * no=0, yes=1

* ( Çok kullanılan işlem değildir)

In [47]:
from sklearn.preprocessing import LabelEncoder

In [48]:
le=LabelEncoder()
y=le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [49]:
print(x)
print(y)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]


# 7.Veri setini ikiye bölme

* Matematiksel modeli bulabilmek için verisetini ikiye bölüyoruz

* öğrenme ve test verisinin boyutunu belirleyebiliriz
* öğrenme verisi matematiksel modeli bulmaya yarar ve algoritmanın öğrenmesini sağlar
* test verisi de bunun doğruluğunu ölçmek için kullanılır
* genelde öğrenme %80, test%20 kullanılıyor

* split fonksiyonu 4 ayrı değişken döndürür;
    * X_train öğrenme verisinin bağımısz değişkeni
    * y_train öğrenme verisinin bağımlı değişken kısmı
    * X_test x verisinin test kısmı
    * y_test y verisinin test kısmı

In [53]:
from sklearn.model_selection import train_test_split
X_ogren,X_test,y_ogren,y_test = train_test_split(x,y,test_size=0.2) 
#test size test verisinin boyutunu belirler (%20 olarak belirledik)

In [54]:
print(X_ogren)

[[0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 0.0 44.0 72000.0]]


In [55]:
print(X_test)

[[1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [56]:
print(y_ogren)

[0 0 0 1 0 1 1 0]


In [57]:
print(y_test)

[1 1]


# 8.Özellikleri Ölçekleme

* Bütün özelliklerin aynı ölçekte işlem görmesini sağlar
* Bazı özelliklerin diğer özellikleri domine etmesinden kaynaklı kullanılır
* Bütün değerler aynı aralıkta olur

#### standardisation(standardizasyon)
* x(std) = [x-ort(x)] / standart_sapma(x)
* Her zaman çalışır ancak normal dağılımlarda kullanılması önerilmez

#### normalisation (Normalleştirme)
* x(norm) = [x-min(x)]/[max(x)-min(x)]
* Normal dağılımlarda kullanılması önerilir

#### ÖNEMLİ NOT !!!!!
* Özellikleri ölçeklemeyi verisetini öğrenme ve test şeklinde ikiye böldükten sonra sadece öğrenme verisinde uygulamalıyız

In [58]:
from sklearn.preprocessing import StandardScaler

In [61]:
scaler=StandardScaler()

In [64]:
X_ogren[:,3:]=scaler.fit_transform(X_ogren[:,3:]) 
#fit fonksiyonu hesaplamayı yapar, transfor ise o hesaplamayı taşır
X_test[:,3:] = scaler.transform(X_test[:,3:])
#test verisinde fitlemeye gerek yok çünkü train kısmında hesaplama yapıldı

In [63]:
print(X_ogren)
print(X_test)

[[0.0 1.0 0.0 -1.2597958529291027 -0.8388998277785312]
 [0.0 1.0 0.0 1.4001836605868916 1.57048509712047]
 [0.0 0.0 1.0 -0.19580404752270503 -0.25732415625118615]
 [0.0 0.0 1.0 -1.6587927799565019 -1.3373932605162557]
 [0.0 0.0 1.0 -0.0923603997748607 -1.0050643053577728]
 [0.0 1.0 0.0 0.0701939038288944 -0.02654015961335053]
 [1.0 0.0 0.0 1.134185709235292 1.238156141961987]
 [1.0 0.0 0.0 0.6021898065320932 0.6565804704346418]]
[[1.0 0.0 0.0 -0.5948009745501042 -0.5065708726200484]
 [1.0 0.0 0.0 -0.32880302319850474 0.24116927648653821]]
